project_id = "anhglcjmbkqezqfyunby"

[functions.ai-chat]
verify_jwt = true

[functions.create-enrollment]
verify_jwt = true

[functions.create-meet-link]
verify_jwt = true

[functions.upload-to-drive]
verify_jwt = true

[functions.razorpay-create-order]
verify_jwt = true

[functions.razorpay-verify-payment]
verify_jwt = true

[functions.transcribe-video]
verify_jwt = true

[functions.send-email]
verify_jwt = false

[functions.admin-create-instructor]
verify_jwt = true